name = "pulse"
main = "src/worker.ts"
compatibility_date = "2025-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"

# Fill in after running `wrangler d1 create pulse-db`
[[d1_databases]]
binding = "DB"
database_name = "pulse-db"
database_id = "03fa6d2c-ff7e-4302-babb-189dc7242f7a"
migrations_dir = "migrations"

[triggers]
crons = ["*/5 * * * *"]
